
name: cicd-docker
on:
  workflow_dispatch:
jobs:
  cicd-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DC_USERNAME }}
          password: ${{ secrets.DC_PASSWORD }}
      - name: docker pull existing image
        run: docker pull nginx:latest
      - name: docker new
        run: docker tag nginx:latest ${{ vars.DC_USERNAME }}/hub-nginx:latest
      - name: push image
        run: docker push ${{ vars.DC_USERNAME }}/hub-nginx:latest
      - name: list image
        run: ls image 
