name: docker
on: workflow_dispatch
jobs:
 dockertest:
   runs-on: ubuntu-latest
   steps:
     - name: docker login
       run: echo "${{ secrets.DC_PASSWORD }} | docker login -u jithesh0017" --password-stdin
     - name: pull existing image
       run: docker pull nginx:latest
     - name: rename image
       run: docker tag nginx:latest ${{ vars.DC_USERNAME }}/nginx:latest
     - name: push image to docker hub
       run: docker push ${{ vars.DC_USERNAME }}/nginx:latest
     - name: docker image list
       run: ls image
