name: docker-login
on: workflow_dispatch
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: echo "${{secrets. DOCKER_PASSWORD }} | docker login -u jithesh0017" ${{ vars.DOCKER_USERNAME }} --password-stdin
      - name: pull existing image
        run: docker pull doit:latest
      - name: rename image
        run: docker image tag doit:latest ${{ vars.DOCKER_USERNAME }}/doit:latest
      - name: image list
        run: docker image ls
      - name: push request
        run: docker push ${{ vars.DOCKER_USERNAME }}/doit:latest
      
