name: docker-login
on: workflow_dispatch
jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }} | docker login -u jithesh0017" ${{ vars.DOCKER_USERNAME }} --password-stdin
      - name: docker pull
        run: docker pull image nginx:latest
      - name: docker rename image
        run: docker image tag nginx:latest ${{ vars.DOCKER_USERNAME }}/nginx:latest
      - name: docker push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/nginx:latest
      
