name: docker-login
on: workflow_dispatch
jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@3.4.0
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}
      
