name: docker-login
on: workflow_dispatch
jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }} | docker login -u jithesh0017" ${{ vars.DOCKER_USERNAME }} --password-stdin
      
