name: docker hub login
on:
  workflow_dispatch:
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker pull existing image
        run: docker pull nginx:latest
      - name: docker new
        run: docker tag nginx:latest ${{ vars.DOCKER_USERNAME }}/git-nginx:latest
      - name: push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/git-nginx:latest
