name: docker-login
on: workflow_dispatch
jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }} | docker login -u jithesh0017" ${{ vars.DOCKER_USERNAME }} --password-stdin
      - name: pull existing image
        run: docker pull nginx:latest
      - name: rename the image
        run: docker image tag nginx:latest ${{ vars.DOCKER_USERNAME }}/jithesh:doit
      - name: push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/nginx:latest
      
