name: hub
on: workflow_dispatch
jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DC_USERNAME }}
          password: ${{ secrets.DC_PASSWORD }}
      - name: docker pull image
        run: docker pull nginx:latest
      - name: docker rename image
        run: docker tag nginx:latest ${{ vars.DC_USERNAME }}/new-nginx:latest
      - name: push docker hub
        run: docker push ${{ vars.DC_USERNAME }}/new-nginx:latest
      - name: image list
        run: docker image ls
    
